name: DevSecOps CI-CD Pipeline_vnew1

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: namespace/appcode-ecr
  ECR_REGISTRY: 188776114860.dkr.ecr.eu-north-1.amazonaws.com
  IMAGE_TAG: ${{ github.sha }}

jobs:

  test-build-scan-push:
    runs-on: ubuntu-latest

    steps:

      # ---------------- CHECKOUT ----------------
      - name: Checkout App Repo
        uses: actions/checkout@v4

      # ---------------- PYTHON SETUP ----------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ---------------- INSTALL DEPENDENCIES ----------------
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      # ---------------- DEBUG ----------------
      - name: Debug Repository Structure
        run: |
          pwd
          find .

      # ---------------- RUN TESTS ----------------
      - name: Run Unit Tests
        run: |
           python -m pytest tests/test_app.py -v

      # ---------------- AWS LOGIN ----------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ---------------- LOGIN TO ECR ----------------
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ---------------- INSTALL TRIVY ----------------
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget -y
          TRIVY_VERSION=0.70.0
          wget https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
          tar -xzf trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      # ---------------- TRIVY FS SCAN ----------------
      - name: Trivy Filesystem Scan
        run: |
          trivy fs . \
          --severity HIGH,CRITICAL \
          --exit-code 1

      # ---------------- BUILD IMAGE ----------------
      - name: Build Docker Image
        run: |
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      # ---------------- TRIVY IMAGE SCAN ----------------
      - name: Trivy Docker Image Scan
        run: |
          trivy image \
          --severity HIGH,CRITICAL \
          --ignore-unfixed \
          --exit-code 1 \
          $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # ---------------- PUSH IMAGE ----------------
      - name: Push Docker Image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # ---------------- CHECKOUT HELM REPO ----------------
      - name: Checkout Helm Repository
        uses: actions/checkout@v4
        with:
          repository: Tulajaram12/helmact
          token: ${{ secrets.GH_PAT }}
          path: helmact

      # ---------------- UPDATE VALUES.YAML ----------------
      - name: Update Helm values.yaml Image Tag
        run: |
          cd helmact

          sed -i "s|tag:.*|tag: \"$IMAGE_TAG\"|g" values.yaml

          echo "Updated values.yaml:"
          cat values.yaml

      # ---------------- COMMIT AND PUSH ----------------
      - name: Commit and Push Changes
        run: |
          cd helmact

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "Update image tag to $IMAGE_TAG" || echo "No changes to commit"

          git push
